language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
script: 'bundle exec rspec spec'

notifications:
  email:
    - tam.eastley@gmail.com
    - susanne.dewein@gmail.com
    - carsten.zimmermann@absolventa.de
    - felix@mohnert.de
