language: ruby
rvm:
- 2.1.0
- 2.2.2
- 2.3.0
script: bundle exec rspec spec
notifications:
  email:
  - tam.eastley@gmail.com
  - susanne.dewein@gmail.com
  - felix@mohnert.de
  webhooks:
    secure: YgIzmRfVkBhyjLeEhtnGuZ4s0J3jw1jBxrP0qh6VLx+I2bGszuv1VJAAKhhUmqXi5qyAaOeNRKYmwE1UN8P6UupmtNpxBPpki+tzZ07rHkNqC9EkCg2NgzhcNV654XjXQNEyUb4I54bpbMbQXa+aX3RokfuxWR4ernb61TelwjU=
